### ISSUE TITLE
Instructions for Windows

### ISSUE THREAD

**Issue by mecklaiz** [fhir-crucible/crucible#107]
I've got this project running on a Windows server and was wondering if anyone would be interested in the instructions for getting set up there. If so please let me know and I'll be happy to document what I've found.

**Comment by andrequina** [comment]
Sorry, missed this issue coming in.  We would be happy to post windows instructions to our Wiki if you have them.

**Comment by mecklaiz** [comment]
Cool, I'll draft something up in the next couple of days and send it to you for review.

**Comment by kaverianov1** [comment]
Please let me know if you still have instructions for Windows handy. Will help me a lot.
Thank you in advance.

**Comment by mecklaiz** [comment]
Unfortunately, i have long since left the job where i did this work. Let me see if any of my ex-colleagues still have this information. I apologize for never having completed this task.
