### ISSUE TITLE
Crucible is using "GET [base]/[resource]?_search= " but this type of search is not documented in the FHIR specification for DSTU2

### ISSUE THREAD

**Issue by CorinaCiocanea** [fhir-crucible/crucible#112]
![i53 cimgpsh_orig](https://cloud.githubusercontent.com/assets/13314456/12327499/995c50d8-badf-11e5-8b02-3da3ba10eab2.png)

The specification (http://hl7.org/fhir/http.html#search) says we should support search using "_search" only for POST.

I am not sure if this issue should be added on this project or the "plan_executor" one. Please let me know if I should change the project.

**Comment by andrequina** [comment]
Search request HTTP method has been fixed.
