### ISSUE TITLE
No way to run other tests suites after running a test suite without going back to server through front page.

### ISSUE THREAD

**Issue by douglas-andrew-harley** [fhir-crucible/crucible#135]
When you are testing a FHIR server, running one suite at-a-time, after a suite completes there is no way to run a different suite, you can only see previous test runs. In order to run a dofferent suite, you need to go back to the main page, and then click on the target server, and then select and run the desired suite.

SUGGESTION: It might make more sense to add a new tab "Test Runs", instead of munging that under the "Tests" tab.

**Comment by arscan** [comment]
You should be able to click on the "x" next to the date of the test run that you are currently looking at to clear out the results.  Then you will be able to choose other suites to run.  See attached screenshot.

Thanks for the feedback on the tabs.  We have been looking at reorganizing them, and we'll consider your suggestion.

![screen-shot-2016-03-17-at-2 20 50-pm](https://cloud.githubusercontent.com/assets/412901/13856902/d79ec14c-ec4d-11e5-8058-03983009d611.jpg)

**Comment by douglas-andrew-harley** [comment]
Aha, thanks!...I thought that meant to delete those test results.

**Comment by arscan** [comment]
Ah, interesting, we hadn't thought that it would be interpreted that way. We'll take a look at making that more clear in the future as well.  Thanks again.
