### ISSUE TITLE
select/deselect all suites widget icon does not revert back to checkmark after clearing past test run in cases where it was used to select all tests

### ISSUE THREAD

**Issue by douglas-andrew-harley** [fhir-crucible/crucible#136]
here is how it looks initially:
![image](https://cloud.githubusercontent.com/assets/12547857/13925468/c8f3905a-ef5e-11e5-82e6-118d7b0bba76.png)

here is how it looks after running all tests in a suite:
![image](https://cloud.githubusercontent.com/assets/12547857/13925614/5a23ea8e-ef5f-11e5-9d89-dcefbb0396a7.png)

and here is how it looks after clearing the just-ran past test data:
![image](https://cloud.githubusercontent.com/assets/12547857/13925637/6bcef026-ef5f-11e5-92b8-c5181f14e1cd.png)

it should revert back to the checkmark icon, which is _does_ do if only a single test is done.

**Comment by andrequina** [comment]
thanks.  I'll take a look.

**Comment by arscan** [comment]
Thanks for identifiying this issue @douglas-andrew-harley, I just put in a fix for this.  I also noticed similar issues with the check all / uncheck all button, so I went ahead and fixed too.  It'll might take a few days for us to deploy this out to our servers.

**Comment by arscan** [comment]
Ah, sorry, I mispoke, I meant to say that I also noticed a similar issue with the expand/collapse button as well, which is also fixed.

**Comment by douglas-andrew-harley** [comment]
No prob...thanks for fixing.

Cheers,
Doug

**Comment by jawalonoski** [comment]
Rob, is this issue resolved? If so, please close.

**Comment by arscan** [comment]
This issue should be fixed.  Thanks for reporting it!
