### ISSUE TITLE
Unable to complete CentOS 7 installation

### ISSUE THREAD

**Issue by CarthageKing** [fhir-crucible/crucible#190]
Hi,

I followed the instructions you have for installing Crucible on CentOS 7. Everything looked good until the part where I have to open Firefox and navigate to port 80 (i.e. http://localhost). At this point, Firefox attempts to redirect me to https://localhost and then an "Unable to connect" message is shown. I'm stuck at this point.

Any idea what's wrong? Or logs I should look check or things I should revisit to make sure the installation completes?

BTW, I'm running CentOS on VirtualBox and I'm using Windows 7.

**Comment by okeefm** [comment]
Hello!

If you're running Crucible on VirtualBox, the network location of the application might be different than running it directly on your local machine. I would recommend starting by looking at the VirtualBox network settings for the VM running Crucible, which you can find by right-clicking on the VM in the VirtualBox Manager window, clicking "settings", then clicking on the "Network" icon on the top row. 

If the Adapter 1 settings are set to NAT, you will have to forward the port Crucible is listening on (I.E. port 80) from the Guest OS (CentOS in this case) to the host OS (your Windows 7 machine). These setttings are under the "Advanced" button on the Network settings page, and you can find more information about setting them at [this link](https://nsrc.org/workshops/2014/sanog23-virtualization/raw-attachment/wiki/Agenda/ex-virtualbox-portforward-ssh.htm). 

Let me know if this helps, or if you have any additional questions.

**Comment by CarthageKing** [comment]
I'm closing this. I could never get production to work, so I just went ahead and started Crucible in development mode.

This works for my use case as of the moment.
