### ISSUE TITLE
Crucible - FHIR Testing ... Test Validation and Test Verification

### ISSUE THREAD

**Issue by Interopguy** [fhir-crucible/crucible#209]
<p>The following example is a single occurrence and a random deep dive on a single test case (it is representative of the types of issues being located and reported on - be advised we cannot report on or provide documented input to all the related/similar issues being identified throughout Crucible).  Our report is more to provide an overall assessment and software quality review into the test "process" than this particular error submission.</p>
<p>For the purpose of this report we will be speaking to Crucible production release against STU3 version 1.6.</p>
<p>For the purpose of this report the SUT (System Under Test) could be any HL7 FHIR STU3 version 1.6 implementation with server side validation turned on (so the server is validating the exchange of messages between a client and server).</p>
<p>For our report we will be using the test - "X010  Condition: Create New" (found under the Clinical Resource Test Suite) (Crucible message attached as an example).</p>
---
<p>1. Value sets and coded values - FHIR defines Languages Value Set here (<a href="http://hl7.org/fhir/2016Sep/valueset-languages.html">http://hl7.org/fhir/2016Sep/valueset-languages.html</a>)<br>
Sample Crucible message ... denotes en-US as being used.<br>
xml version="1.0" encoding="utf-8"<br>
Condition xmlns="http://hl7.org/fhir"<br>
language value="en-US"</p>

<p>Sample of valid FHIR Client message ... according to FHIR published standards<br>
xml version="1.0" encoding="utf-8"<br>
Condition xmlns="http://hl7.org/fhir"<br>
language value="en"</p>
---
<p>2. Value sets and coded values identifier and identifier-type (<a href="http://hl7.org/fhir/valueset-identifier-type.html">http://hl7.org/fhir/valueset-identifier-type.html</a>) - includes coded values for display value<br>
Sample Crucible message ... denotes random generated values as being used.<br>
display value="LBCEub3uT+9Du/AjZ5+4Ww=="</p>

<p>Sample of valid FHIR Client message ... according to FHIR published standards<br>
display value="Filler Identifier"</p>
---
<p>3. Value sets and coded values category (<a href="http://hl7.org/fhir/valueset-condition-category.html">http://hl7.org/fhir/valueset-condition-category.html</a>)<br>
Sample Crucible message ... denotes random generated values as being used.<br>
display value="lo7PNT44qxChlTvBu8rmEA=="</p>

<p>Sample of valid FHIR Client message ... according to FHIR published standards<br>
display value="Finding"</p>
---
<p>4. Value sets and coded values severity (<a href="http://snomed.info/sct">http://snomed.info/sct</a>)<br>
Sample Crucible message ... denotes random generated values as being used.<br>
display value="Xl7yj5HCtO+8/O7tW+/B4g=="</p>

<p>Sample of valid FHIR Client message ... according to FHIR published standards<br>
display value="Mild"</p>
---
<p>5. Value sets and coded values onsetRange (<a href="http://hl7.org/fhir/2016Sep/datatypes.html#Range">http://hl7.org/fhir/2016Sep/datatypes.html#Range</a>)<br>
Sample Crucible message ... denotes random generated values as being used.<br>
unit value="TdXRLbDXmoEdj58YZag4Nw=="</p>

<p>Sample of valid FHIR Client message ... according to FHIR published standards<br>
unit value="drams"</p>
---
<p>6. Complex but related data values such as abatementRange (low and high values) <br>
e.g. the low value is higher than the high value (fails simple validation rules)<br>
Sample Crucible message ... denotes random generated values as being used.<br>
low value value="0.14087090599202667"<br>
high value value="0.0935924878064125"</p>

<p>A common adage among Testers is our need to ensure we "Test-the-Test" -  (ISO refers to this as Test Calibration) as a custodian of quality assurance reporting - "we" as the testing community are held to higher degree and a level of quality and assurances above all others.  Reporting either a false-positive or a false-negative can have dire consequences.</p>

[ConditionCreate_Original.txt](https://github.com/fhir-crucible/crucible/files/688674/ConditionCreate_Original.txt)

**Comment by jawalonoski** [comment]
1. While `en-US` is not in the valueset, it is in `BCP-47` which this valueset is supposed to represent. This has been brought up before and is in fact an error in FHIR.

2-5. Yes, we use randomly generated strings. There is no invariant that demands that the `display` value must match the `code`. So in fact, this is perfectly acceptable according to the FHIR standard.

6. Thank you for finding this error.
