### ISSUE TITLE
How to clear out "Recent common failures" list?

### ISSUE THREAD

**Issue by CarthageKing** [fhir-crucible/crucible#215]
Hi,

This is a dumb question and I might be missing something, but how do I tell Crucible to clear out the "Recent common failures" list?

I saw the projectcrucible.org was updated to support FHIR 1.8.0. I reexecuted tests on our server. I navigated to the Server Summary tab to look at the failed tests. It says there that the server still has "Unknown resource type MedicationOrder" error. As far as I know, this resource existed in FHIR 1.6.0 but was removed in later FHIR versions.

I wanted to clear out this error as it doesn't apply anymore to the latest FHIR version.

Best Regards,

**Comment by arscan** [comment]
Hi @CarthageKing  -- that does sound like a bug.  I am on travel all day tomorrow but I'll take a look at this as soon as I can.

**Comment by jawalonoski** [comment]
@CarthageKing we deployed Pull Request #218 that should have resolved this issue. Does it look fixed to you?

**Comment by CarthageKing** [comment]
Yes, I can confirm that the MedicationOrder faliures are not showing up in projectcrucible.org now.

Thank you.

Best Regards,
