### ISSUE TITLE
trailing "/" in history interaction

### ISSUE THREAD

**Issue by msfyuksel** [fhir-crucible/crucible#234]
The history interaction signatures are defined as follows:
  GET [base]/[type]/[id]/_history{?[parameters]&_format=[mime-type]}
  GET [base]/[type]/_history{?[parameters]&_format=[mime-type]}
  GET [base]/_history{?[parameters]&_format=[mime-type]}

However, all crucible history interactions without any specific parameter or format have an extra trailing "/", e.g. [base]/EligibilityResponse/61cba955-4474-41ec-8e60-b8cbed78dabc/_history/

Could you please remove the "/" at the end? Thanks.

**Comment by arscan** [comment]
Hmmm, this should have been fixed, and deployed on Sunday.  https://github.com/fhir-crucible/fhir_client/issues/57

But apparently it is still happening.  I'll see if I can track down the problem.  Thanks for the bug report.

**Comment by arscan** [comment]
Seems to be working properly on our STU3 server (www.projectcrucible.org) in the "Resource Test: Read History of existing" test.

![screen shot 2017-06-01 at 12 44 51 pm](https://cloud.githubusercontent.com/assets/412901/26690659/21180088-46c8-11e7-9274-f15b307afd79.png)

I'm going to go ahead an close this.  If there is a specific instance where it is breaking, please let me know which site (STU3 or DSTU2, which test against what server).
