### ISSUE TITLE
Tests should add a common tag to all resources they create in order to simplify cleanup

### ISSUE THREAD

**Issue by jamesagnew** [fhir-crucible/crucible#235]
The crucible test executor has a tendency to leave behind resources like this one: http://fhirtest.uhn.ca/baseDstu3/Questionnaire/29870

These tend to be filled with blocks like the following:
```json
 "system": "http://projectcrucible.org/T8ggfo88CsW/TCBMD0d/Ig==",
      "value": "PIuwu0RYu5Lrj2nlUBW8XA==",
      "assigner": {
        "identifier": {
          "use": "usual",
          "system": "http://projectcrucible.org/6rrAksJJK+JcULS37d4cmA==",
          "value": "cumvCmOPy0HZRA8Sb/iQSg=="
        },
        "display": "Organization Zkc4doWzpbK7eyWFan/ZLg=="
      }
```

Unfortunately if these don't get cleaned up by the test executor they get annoying for other users of the public server because they are filled with nonsense.

Would it be possible to have a common tag added to all resources created by the test executor in order to simplify cleanup by server owners periodically?

**Comment by jawalonoski** [comment]
Sure. We try (but apparently do not always succeed) in cleaning up after ourselves. What sort of tag are you looking for precisely? Something in `Resource.meta.tag`?

**Comment by jawalonoski** [comment]
Another option is to delete any resources with an `identifier` with a `system` that starts with `http://projectcrucible.org` -- I'm fairly certain all of our randomly generated "nonsense" resources have such identifiers.
