### ISSUE TITLE
Remove a FHIR Server from testing?

### ISSUE THREAD

**Issue by CarthageKing** [fhir-crucible/crucible#257]
Hi,

Is there a way from the https://projectcrucible.org website on how to remove a FHIR server from testing?

We deployed a new version of our FHIR server aligned to version 3.0.1 in a separate URL. The old one on FHIR 1.8.0 is still publicly available in its original URL but we want to remove that since https://projectcrucible.org doesn't really test with 1.8.0 anymore.

**Comment by jawalonoski** [comment]
Yes. Right now the only way to remove a server is to ask us. @arscan will coordinate with you.

**Comment by CarthageKing** [comment]
Thank you.

Please remove https://ipsdemo.accentureanalytics.com/fhir/v1.0.0 (named IPS FHIR Server 1.8.0) from testing.

**Comment by arscan** [comment]
I removed the server, so it is no longer visible and won't be tested again (unless you reenter in the server url directly and run more tests manually).  Could you confirm that the right server is no longer showing up?  Thanks!

**Comment by CarthageKing** [comment]
Thanks. I can confirm the aforementioned server is removed from https://projectcrucible.org/.

Closing this ticket.
