### ISSUE TITLE
STU3 test create requests Content-Type header is no longer conformant.

### ISSUE THREAD

**Issue by pcosmog** [fhir-crucible/crucible#293]
The STU3 specification (https://www.hl7.org/fhir/STU3/http.html#mime-type) says: 

"requests and responses **SHALL explicitly** set the character encoding to UTF-8 using the charset parameter of the MIME-type in the **Content-Type** header."

The crucible tests have recently changed such that they are no longer explicitly setting the character encoding to UTF-8 when creating resources in any of the "Base Resources", "Clinical Resources", "Foundation Resources" and "Specialized Resources" test suites. 

For example, the headers sent in the "Appointment: Create New" step of the "Resource Test Appointment" test in the "Base Resources" test suite are now (as of March 19, 2019):

    User-Agent: Ruby FHIR Client
    Accept-Charset: utf-8
    Accept: application/fhir+json
    Content-Type: application/fhir+json

They were previously (at least as recently as Jan 22, 2019) as follows:

    User-Agent: Ruby FHIR Client
    Content-Type: application/fhir+json;charset=UTF-8
    Accept-Charset: UTF-8
    Accept: application/fhir+json
    resource: FHIR::Appointment
    format: application/fhir+json

Note the difference in the Content-Type header:

old, **good** = Content-Type: application/fhir+json;**charset=UTF-8**
new, **bad** = Content-Type: application/fhir+json

As a result of this change, our now (correctly) server rejects most requests, and most tests now (incorrectly) fail.

**Comment by radamson** [comment]
Thanks for the report!  This is a critical issue that was introduced in another PR that was cleaning up some of the unnecessary or invalid headers in the underlying client.  We have a fix in process and we'll get it live asap.

**Comment by arscan** [comment]
Hi @pcosmog -- we just deployed the fix.  If you have a chance could you try it out to confirm it is now what you expect?  Thanks for the report!

**Comment by pcosmog** [comment]
Confirmed
