### ISSUE TITLE
Bundle.total is optional, but crucible tests require it?

### ISSUE THREAD

**Issue by pcosmog** [fhir-crucible/crucible#297]
I believe the Bundle.total element is optional in the STU3 spec, for example, in the Paging section (http://hl7.org/fhir/STU3/http.html#paging), it states:

"A server MAY inform the client of the total number of resources returned by the interaction for which the results are paged using the Bundle.total."

Crucible tests seem to require Bundle.total. For example, in the "Core Functionality" test suite, the "History Test" will fail if the "History for specific resource" call does not return Bundle.total.

The error msg provided reads:

"the number of returned versions is not correct Expected: 3, but found: ."

Note that no value is provided in the "but found ." part of the message. And in fact, look at the request and response body, it is clear that 3 Bundle entries were correctly returned. It seems the test did not count the number of bundle entries, but is instead relying on Bundle.total?

**Comment by arscan** [comment]
Thanks for all the issue reports! We deployed an update so that we don't rely on total for those checks.  Could you try it out when you have a chance?  Thanks!

**Comment by pcosmog** [comment]
This is fixed now - thanks!
