### ISSUE TITLE
Crucible passes an invalid sopClass

### ISSUE THREAD

**Issue by pcosmog** [fhir-crucible/crucible#300]
When crucible attempts to create an imaging study, it passes us:

"sopClass": "urn:oid:2",

The "sopClass" element is of type oid (http://hl7.org/fhir/STU3/imagingstudy.html)

The regex for validating an oid in the spec is (http://hl7.org/fhir/STU3/datatypes.html#oid):
`urn:oid:[0-2](\.[1-9]\d*)+`

You can use a regex tester (like https://regex101.com/) to see that "urn:oid:2" does not pass this regex, it's invalid. It needs to have at least one period followed by a number.

Our server rejects the create attempt due to the invalid OID, and Crucible is incorrectly failing the test as a result.

**Comment by arscan** [comment]
Deployed a fix, thanks.  There was a ~8% chance that a given oid was invalid.  Let me know if it looks ok on your end.

**Comment by pcosmog** [comment]
Confirmed fixed.
