### ISSUE TITLE
Run test cases - Server not responding now

### ISSUE THREAD

**Issue by singhmanjeet1982** [fhir-crucible/crucible#321]
Hi,
I tried running crucible test cases on my FHIR server
https://mkw-msl-dev-fhirsv-api-au-se.azurewebsites.net

Inititally test passed and then if started failing & hanged for days. Now I am not able to GET 'https://mkw-msl-dev-fhirsv-api-au-se.azurewebsites.net/Patient' but 'metadata' is working fine.

Can you guide, if there is something I need to check at server level

Thanks

**Comment by jawalonoski** [comment]
@singhmanjeet1982 You should investigate your server logs to see if you can get details on the exception being reported in the `OperationOutcome` responses you are seeing from the `Patient` endpoint. There appears to be an internal error on your server -- we can't help you debug that.
