### ISSUE TITLE
Conformance test

### ISSUE THREAD

**Issue by singhmanjeet1982test** [fhir-crucible/crucible#323]
Hi,
I have test run FHIR server using Crucible. I got the score of 85%.
Can you please explain what this score signifies. Is this good score for FHIR server to be used as production.  And also, what needs to be done to increase its score to 90+.

Thanks 
Manu

**Comment by jawalonoski** [comment]
The score represents the coverage of how much of the FHIR standard the server successfully supports according to the Crucible tests.

The score by itself is not a good measure of whether or not the server should be used in production, it is only one benchmark. The section that pass or fail should be weighed against your requirements. Don't need Bundle transactions? Then it doesn't matter if you pass those or not. Really need all types of search support? Then check to see that your server passes those tests.
